language: c
matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - g++-5
            - make
            - libglfw3 
            - libglfw3-dev
            - libfreetype6-dev 
            - libssl-dev
    - os: windows
      language: sh
      filter_secrets: false
    - os: osx
      osx_image: xcode10.2
      addons:
        homebrew:
          packages:
            - freetype
            - glfw
            - openssl
script:
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc
    fi
  - |
    if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      export LIBRARY_PATH=$LIBRARY_PATH:/usr/local/opt/openssl/lib/
    fi    
  - |
    if [[ "${TRAVIS_OS_NAME}" == "windows" ]]; then
      choco install openssl.light
      echo "Testing msvc bootstrapping"
      ./make_msvc.bat
      echo "Running make_tests.bat..."
      ./make_tests.bat
    fi
  - |
    if [[ "${TRAVIS_OS_NAME}" != "windows" ]]; then
      make
      ./v install glfw
      make test
    fi
  - |
    if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      git clone https://github.com/vlang/vid
      cd vid && ../v .
    fi    
