language: c
matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - g++-5
            - make
            - libglfw3
            - libglfw3-dev
            - libfreetype6-dev
            - libssl-dev
            - tcc
    - os: windows
      language: sh
      filter_secrets: false
    - os: osx
      osx_image: xcode10.2
      addons:
        homebrew:
          packages:
            - freetype
            - glfw
            - openssl
script:
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc
    fi
  - |
    if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      export LIBRARY_PATH=$LIBRARY_PATH:/usr/local/opt/openssl/lib/
    fi
  - |
    if [[ "${TRAVIS_OS_NAME}" == "windows" ]]; then
      git clone --depth=1 https://github.com/ubawurinna/freetype-windows-binaries  thirdparty/freetype/
      echo "Just running ./make.bat to produce v.exe"
      ./make.bat
      ls -la v.exe
      echo "Running v test v..."
      ./v.exe test v
      ##echo "Running only the repl tests directly"
      ##./v.exe ./compiler/tests/repl/repl_test.v
      echo "Testing gcc bootstrapping"
      ./make.bat -gcc
    fi
  - |
    if [[ "${TRAVIS_OS_NAME}" != "windows" ]]; then
      make
      #./v install glfw
      ./v test v
    fi
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      echo "Ensure that v can build itself with tcc too ..."
      /usr/bin/tcc -version
      ./v -cc /usr/bin/tcc -o vtcc compiler/
      ls -la vtcc
    fi
  - |
    if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      git clone https://github.com/vlang/vid
      cd vid && ../v -debug -o vid .
    fi
