---
blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ General Questions and Answers about V
    url: https://github.com/vlang/v/discussions/categories/questions-and-answers
    about: Please ask and answer questions as a discussion thread
