name: Add voting info to new issue

on:
  issues:
    types:
      - opened

jobs:
  add-voting-info:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Append voting info to issue body
        uses: julien-deramond/update-issue-body@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            > [!NOTE]
            > You can use the ðŸ‘ reaction to increase the issue's priority for developers.
            >
            > Please note that only the ðŸ‘ reaction to the issue itself counts as a vote.
            > Other reactions and those to comments will not be taken into account.
          edit-mode: append
          append-separator: newline
