name: V Symlink Works

on:
  workflow_dispatch:
  push:
    paths:
      - 'cmd/tools/vsymlink.v'
      - '.github/workflows/check_symlink_works.yml'
  pull_request:
    paths:
      - 'cmd/tools/vsymlink.v'
      - '.github/workflows/check_symlink_works.yml'

jobs:
  check-ubuntu:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout V
        uses: actions/checkout@v4
      - name: Build V
        run: make && ./v symlink -githubci
      - name: Check if V is usable
        run: |
          pwd
          v version
          cd ~
          pwd
          v version
          echo 'println(123)' > hi.v
          v run hi.v
          echo "Everything was fine :rocket:" >> $GITHUB_STEP_SUMMARY

  check-macos:
    runs-on: macos-13
    steps:
      - name: Checkout V
        uses: actions/checkout@v4
      - name: Build V
        run: make && ./v symlink -githubci
      - name: Check if V is usable
        run: |
          pwd
          v version
          cd ~
          pwd
          v version
          echo 'println(123)' > hi.v
          v run hi.v
          echo "Everything fine on macos too :rocket:" >> $GITHUB_STEP_SUMMARY

  check-windows:
    runs-on: windows-2019
    shell: bash
    steps:
      - name: Checkout V
        uses: actions/checkout@v4
      - name: Build V
        run: |
          .\make.bat
          .\v.exe symlink -githubci
      - name: Check if V is usable
        run: |
          pwd
          v version
          cd c:\
          pwd
          v version
          echo 'println(123)' > hi.v
          v run hi.v
          echo "All fine on Windows as well :rocket:" >> $GITHUB_STEP_SUMMARY
