name: CI
on: [push, pull_request]
jobs:

  ubuntu-tcc:
    runs-on: ubuntu-18.04
    env:
      VFLAGS: -cc tcc
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: sudo rm -f /etc/apt/sources.list.d/dotnetdev.list /etc/apt/sources.list.d/microsoft-prod.list; sudo apt-get update; sudo apt-get install --quiet -y libglfw3 libglfw3-dev libfreetype6-dev libssl-dev sqlite3 libsqlite3-dev libsdl2-dev libsdl2-ttf-dev libsdl2-mixer-dev libsdl2-image-dev
    - name: Build v
      run: echo $VFLAGS && make -j4 && ./v -cg -o v v.v
    - name: Test v->c
      run: |
        sudo ln -s /var/tmp/tcc/bin/tcc /usr/local/bin/tcc
        tcc -version
        ./v -o v2 v.v # Make sure vtcc can build itself
        ./v test-compiler
    - name: Test v binaries
      run: ./v build-vbinaries

  alpine-docker-musl-gcc:
    name: alpine-musl
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v1

    - name: Build V
      uses: spytheman/docker_alpine_v@v6.0
      with:
        entrypoint: .github/workflows/alpine.build.sh

    - name: Test V
      uses: spytheman/docker_alpine_v@v6.0
      with:
        entrypoint: .github/workflows/alpine.test.sh

  macos:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-10.14, macOS-latest]
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install dependencies
      run: |
        brew install freetype glfw openssl postgres sdl2 sdl2_ttf sdl2_mixer sdl2_image
        export LIBRARY_PATH="$LIBRARY_PATH:/usr/local/opt/openssl/lib/"
    - name: Build V
      run:  make -j4 && ./v -cg -o v v.v
    - name: Build V using V
      run:  ./v -o v2 v.v && ./v2 -o v3 v.v
    - name: Test symlink
      run:  sudo ./v symlink
    - name: Set up pg database
      run: |
        brew services start postgresql
        sleep 3
        psql -d postgres -c 'select rolname from pg_roles'
        psql -d postgres -c 'create database customerdb;'
        psql -d customerdb -f examples/database/pg/mydb.sql
    - name: Test v->c
      run: ./v test-compiler
    - name: Test v binaries
      run: ./v build-vbinaries
#    - name: Test v->js
#      run: ./v -o hi.js examples/hello_v_js.v && node hi.js
    - name: Test symlink
      run:  ./v symlink && v -o v2 v.v
    - name: Test vsh
      run:  ./v examples/v_script.vsh
    - name: Test vid
      run: |
        git clone --depth 1 https://github.com/vlang/vid.git
        cd vid && ../v -o vid .

  ubuntu:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install dependencies
      run: sudo rm -f /etc/apt/sources.list.d/dotnetdev.list /etc/apt/sources.list.d/microsoft-prod.list; sudo apt-get update; sudo apt-get install --quiet -y postgresql libpq-dev libglfw3 libglfw3-dev libfreetype6-dev libssl-dev sqlite3 libsqlite3-dev libsdl2-dev libsdl2-ttf-dev libsdl2-mixer-dev libsdl2-image-dev
    - name: Build V
      run: make -j4 && ./v -cc gcc -o v v.v
    - name: Test V
      run: ./v test-compiler
    - name: Test v binaries
      run: ./v build-vbinaries
#    - name: Test v->js
#      run: ./v -o hi.js examples/hello_v_js.v && node hi.js
    - name: Build Vorum
      run: git clone --depth 1 https://github.com/vlang/vorum && cd vorum && ../v . && cd ..
    - name: Freestanding
      run: ./v -freestanding -o bare vlib/os/bare/bare_example_linux.v
    - name: x64 machine code generation
      run: cd examples/x64 && ../../v -x64 hello_world.v && ./hello_world


  ubuntu-prebuilt:
    runs-on: ubuntu-18.04
    steps:
    - name: Install dependencies
      run: sudo rm -f /etc/apt/sources.list.d/dotnetdev.list /etc/apt/sources.list.d/microsoft-prod.list; sudo apt-get update; sudo apt-get install --quiet -y postgresql libpq-dev libglfw3 libglfw3-dev libfreetype6-dev libssl-dev sqlite3 libsqlite3-dev libsdl2-dev libsdl2-ttf-dev libsdl2-mixer-dev libsdl2-image-dev
    - name: Download V
      run: wget https://github.com/vlang/v/releases/latest/download/v_linux.zip && unzip v_linux.zip && ./v --version
    - name: Test V
      run: ./v examples/hello_world.v && examples/hello_world && ./v build-examples


  macos-prebuilt:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-10.14, macOS-latest]
    steps:
    - name: Install dependencies
      run: |
        brew install freetype glfw openssl sdl2 sdl2_ttf sdl2_mixer sdl2_image
        export LIBRARY_PATH="$LIBRARY_PATH:/usr/local/opt/openssl/lib/"
    - name: Download V
      run: wget https://github.com/vlang/v/releases/latest/download/v_macos.zip && unzip v_macos.zip && ./v --version
    - name: Test V
      run: ./v examples/hello_world.v && examples/hello_world && ./v build-examples

  windows-prebuilt:
    runs-on: windows-2019
    steps:
    - name: Download V
      run: echo "test" #wget https://github.com/vbinaries/vbinaries/releases/download/latest/v_windows.zip && unzip v_windows.zip && ./v.exe --version
    - name: Test V
      run: echo "test" #./v.exe examples/hello_world.v && examples/hello_world.exe

  ubuntu-musl:
    runs-on: ubuntu-18.04
    env:
      VFLAGS: -cc musl-gcc
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install dependencies
      run: sudo rm -f /etc/apt/sources.list.d/dotnetdev.list /etc/apt/sources.list.d/microsoft-prod.list; sudo apt-get update; sudo apt-get install --quiet -y musl musl-tools libsdl2-dev libsdl2-ttf-dev libsdl2-mixer-dev libsdl2-image-dev
    - name: Build v
      run: echo $VFLAGS && make -j4 && ./v -cg -o v v.v
    - name: Test v binaries
      run: ./v build-vbinaries
#    - name: Test v->js
#      run: ./v -o hi.js examples/hello_v_js.v && node hi.js

  windows-gcc:
    runs-on: windows-2019
    env:
        VFLAGS: -cc gcc
    steps:
    - uses: actions/checkout@v1
    #- uses: actions/setup-node@v1
    #  with:
    #    node-version: 12.x
    - name: Build
      run: |
        gcc --version
        git clone --depth=1 https://github.com/ubawurinna/freetype-windows-binaries.git thirdparty/freetype/
        .\make.bat -gcc
    - name: Test
      run: |
        .\v.exe test-compiler
      ## v.js dosent work on windows
        #.\v.exe -o hi.js examples/hello_v_js.v
        #node hi.js
    - name: Test v binaries
      run: ./v build-vbinaries

  windows-msvc:
    runs-on: windows-2019
    env:
        VFLAGS: -cc msvc
    steps:
    - uses: actions/checkout@v1
    #- uses: actions/setup-node@v1
    #  with:
    #    node-version: 12.x
    - name: Build
      run: |
        echo %VFLAGS%
        echo $VFLAGS
        git clone --depth=1 https://github.com/ubawurinna/freetype-windows-binaries.git thirdparty/freetype/
        .\make.bat -msvc
    - name: Test
      run: |
        .\v.exe test-compiler
      ## v.js dosent work on windows
        #.\v.exe -o hi.js examples/hello_v_js.v
        #node hi.js
    - name: Test v binaries
      run: ./v build-vbinaries

