name: vlib modules CI

on:
  pull_request:
    paths:
      - 'vlib/**.v'
      - '**/module_docs_ci.yml'
  push:
    paths:
      - 'vlib/**.v'
      - '**/module_docs_ci.yml'

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ !contains(github.ref, 'master')}}

jobs:
  build-module-docs:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Build V
        run: make -j4
      - name: Test v doc
        run: |
          # While the integration tests (executing the v doc command) should install
          # markdown automatically, unit tests won't. Run integration tests first.
          ./v test cmd/tools/vdoc/tests/
          ./v test cmd/tools/vdoc/*.v
      - name: Build module documentation
        run: ./v doc -m -f html vlib/
      - name: Deploy docs to vercel
        if: github.event_name == 'push' && github.repository == 'vlang/v' && github.ref == 'refs/heads/master'
        run: npx vercel --confirm --prod --name vmodules --token ${{ secrets.VERCEL_TOKEN }} vlib/_docs/ || true
