name: Periodic CI

on:
  schedule:
    - cron: '0 */6 * * *'
  push:
    paths:
      - '**/periodic_ci.yml'
  pull_request:
    paths:
      - '**/periodic_ci.yml'

env:
  V_CI_PERIODIC: 1

jobs:
  network:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            cc: tcc
          - os: windows-latest
            cc: msvc
          - os: macos-13
            cc: clang
      fail-fast: false
    runs-on: ${{ matrix.os }}
    if: github.ref == 'refs/heads/master' && github.repository == 'vlang/v'
    env:
      VFLAGS: -cc ${{ matrix.cc }} -d network -showcc
    steps:
      - uses: actions/checkout@v4
      - name: Build
        if: runner.os != 'Windows'
        run: make -j4 && ./v doctor
      - name: Build V (Windows)
        if: runner.os == 'Windows'
        run: ./make.bat -msvc && ./v doctor
      - name: Test
        run: ./v test-self vlib/net
