name: Periodic

on:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  network-tests-ubuntu:
    runs-on: ubuntu-20.04
    if: github.event.ref == 'refs/heads/master' && github.event.repository.full_name == 'vlang/v'
    timeout-minutes: 30
    env:
      V_CI_PERIODIC: 1
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies 1
        run: sudo apt-get install --quiet -y sqlite3 libsqlite3-dev
      - name: Build v
        run: make
      - name: Symlink V
        run: sudo ./v symlink
        ## - name: Run network tests
        ##   run: ./v -d network test vlib/net


  network-tests-macos:
    runs-on: macos-14
    if: github.event.ref == 'refs/heads/master' && github.event.repository.full_name == 'vlang/v'
    timeout-minutes: 30
    env:
      V_CI_PERIODIC: 1
    steps:
      - uses: actions/checkout@v4
      - name: Build V
        run: make
      - name: Symlink V
        run: sudo ./v symlink
      - name: Ensure thirdparty/cJSON/cJSON.o is compiled, before running tests.
        run: ./v examples/json.v
        ## - name: Run network tests
        ##   run: ./v -d network test vlib/net

  network-windows-msvc:
    runs-on: windows-2019
    if: github.event.ref == 'refs/heads/master' && github.event.repository.full_name == 'vlang/v'
    timeout-minutes: 30
    env:
      V_CI_PERIODIC: 1
      VFLAGS: -cc msvc
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          echo %VFLAGS%
          echo $VFLAGS
          .\make.bat -msvc
          ## - name: Run network tests
          ##   run: .\v.exe -d network test vlib/net
